
DM LOG 'CLEAR' LOG;

%LET PATH = P:\SurvivalAnalytics\Project 2;
LIBNAME SASDATA "&PATH.";

OPTIONS COMPRESS=YES;

DATA EMP_DATA_RAW;

INFILE "&PATH.\FermaLogis_Event_Type.csv" DELIMITER = ',' DSD FIRSTOBS=2 TRUNCOVER;
 
INFORMAT ROW_ID BEST32.;
INFORMAT X BEST32.;
INFORMAT AGE BEST32.;
INFORMAT turnover $100.;
INFORMAT type $10.;
INFORMAT BUSINESSTRAVEL $100.;
INFORMAT DAILYRATE BEST32.;
INFORMAT DEPARTMENT $100.;
INFORMAT DISTANCEFROMHOME BEST32.;
INFORMAT EDUCATION BEST32.;
INFORMAT EDUCATIONFIELD $100.;
INFORMAT EMPLOYEECOUNT BEST32.;
INFORMAT EMPLOYEENUMBER BEST32.;
INFORMAT ENVIRONMENTSATISFACTION BEST32.;
INFORMAT GENDER $10.;
INFORMAT HOURLYRATE BEST32.;
INFORMAT JOBINVOLVEMENT BEST32.;
INFORMAT JOBLEVEL BEST32.;
INFORMAT JOBROLE $100.;
INFORMAT JOBSATISFACTION BEST32.;
INFORMAT MARITALSTATUS $50.;
INFORMAT MONTHLYINCOME BEST32.;
INFORMAT MONTHLYRATE BEST32.;
INFORMAT NUMCOMPANIESWORKED BEST32.;
INFORMAT OVER18 $10.;
INFORMAT OVERTIME $10.;
INFORMAT PERCENTSALARYHIKE BEST32.;
INFORMAT PERFORMANCERATING BEST32.;
INFORMAT RELATIONSHIPSATISFACTION BEST32.;
INFORMAT STANDARDHOURS BEST32.;
INFORMAT STOCKOPTIONLEVEL BEST32.;
INFORMAT TOTALWORKINGYEARS BEST32.;
INFORMAT TRAININGTIMESLASTYEAR BEST32.;
INFORMAT WORKLIFEBALANCE BEST32.;
INFORMAT YEARSATCOMPANY BEST32.;
INFORMAT YEARSINCURRENTROLE BEST32.;
INFORMAT YEARSSINCELASTPROMOTION BEST32.;
INFORMAT YEARSWITHCURRMANAGER BEST32.;
INFORMAT BONUS_1 $10.;
INFORMAT BONUS_2 $10.;
INFORMAT BONUS_3 $10.;
INFORMAT BONUS_4 $10.;
INFORMAT BONUS_5 $10.;
INFORMAT BONUS_6 $10.;
INFORMAT BONUS_7 $10.;
INFORMAT BONUS_8 $10.;
INFORMAT BONUS_9 $10.;
INFORMAT BONUS_10 $10.;
INFORMAT BONUS_11 $10.;
INFORMAT BONUS_12 $10.;
INFORMAT BONUS_13 $10.;
INFORMAT BONUS_14 $10.;
INFORMAT BONUS_15 $10.;
INFORMAT BONUS_16 $10.;
INFORMAT BONUS_17 $10.;
INFORMAT BONUS_18 $10.;
INFORMAT BONUS_19 $10.;
INFORMAT BONUS_20 $10.;
INFORMAT BONUS_21 $10.;
INFORMAT BONUS_22 $10.;
INFORMAT BONUS_23 $10.;
INFORMAT BONUS_24 $10.;
INFORMAT BONUS_25 $10.;
INFORMAT BONUS_26 $10.;
INFORMAT BONUS_27 $10.;
INFORMAT BONUS_28 $10.;
INFORMAT BONUS_29 $10.;
INFORMAT BONUS_30 $10.;
INFORMAT BONUS_31 $10.;
INFORMAT BONUS_32 $10.;
INFORMAT BONUS_33 $10.;
INFORMAT BONUS_34 $10.;
INFORMAT BONUS_35 $10.;
INFORMAT BONUS_36 $10.;
INFORMAT BONUS_37 $10.;
INFORMAT BONUS_38 $10.;
INFORMAT BONUS_39 $10.;
INFORMAT BONUS_40 $10.;

FORMAT ROW_ID BEST32.;
FORMAT X BEST32.;
FORMAT AGE BEST32.;
FORMAT turnover $10.;
FORMAT BUSINESSTRAVEL $100.;
FORMAT DAILYRATE BEST32.;
FORMAT DEPARTMENT $100.;
FORMAT DISTANCEFROMHOME BEST32.;
FORMAT EDUCATION BEST32.;
FORMAT EDUCATIONFIELD $100.;
FORMAT EMPLOYEECOUNT BEST32.;
FORMAT EMPLOYEENUMBER BEST32.;
FORMAT ENVIRONMENTSATISFACTION BEST32.;
FORMAT GENDER $10.;
FORMAT HOURLYRATE BEST32.;
FORMAT JOBINVOLVEMENT BEST32.;
FORMAT JOBLEVEL BEST32.;
FORMAT JOBROLE $100.;
FORMAT JOBSATISFACTION BEST32.;
FORMAT MARITALSTATUS $50.;
FORMAT MONTHLYINCOME BEST32.;
FORMAT MONTHLYRATE BEST32.;
FORMAT NUMCOMPANIESWORKED BEST32.;
FORMAT OVER18 $10.;
FORMAT TYPE $100.;
FORMAT OVERTIME $10.;
FORMAT PERCENTSALARYHIKE BEST32.;
FORMAT PERFORMANCERATING BEST32.;
FORMAT RELATIONSHIPSATISFACTION BEST32.;
FORMAT STANDARDHOURS BEST32.;
FORMAT STOCKOPTIONLEVEL BEST32.;
FORMAT TOTALWORKINGYEARS BEST32.;
FORMAT TRAININGTIMESLASTYEAR BEST32.;
FORMAT WORKLIFEBALANCE BEST32.;
FORMAT YEARSATCOMPANY BEST32.;
FORMAT YEARSINCURRENTROLE BEST32.;
FORMAT YEARSSINCELASTPROMOTION BEST32.;
FORMAT YEARSWITHCURRMANAGER BEST32.;
FORMAT BONUS_1 $10.;
FORMAT BONUS_2 $10.;
FORMAT BONUS_3 $10.;
FORMAT BONUS_4 $10.;
FORMAT BONUS_5 $10.;
FORMAT BONUS_6 $10.;
FORMAT BONUS_7 $10.;
FORMAT BONUS_8 $10.;
FORMAT BONUS_9 $10.;
FORMAT BONUS_10 $10.;
FORMAT BONUS_11 $10.;
FORMAT BONUS_12 $10.;
FORMAT BONUS_13 $10.;
FORMAT BONUS_14 $10.;
FORMAT BONUS_15 $10.;
FORMAT BONUS_16 $10.;
FORMAT BONUS_17 $10.;
FORMAT BONUS_18 $10.;
FORMAT BONUS_19 $10.;
FORMAT BONUS_20 $10.;
FORMAT BONUS_21 $10.;
FORMAT BONUS_22 $10.;
FORMAT BONUS_23 $10.;
FORMAT BONUS_24 $10.;
FORMAT BONUS_25 $10.;
FORMAT BONUS_26 $10.;
FORMAT BONUS_27 $10.;
FORMAT BONUS_28 $10.;
FORMAT BONUS_29 $10.;
FORMAT BONUS_30 $10.;
FORMAT BONUS_31 $10.;
FORMAT BONUS_32 $10.;
FORMAT BONUS_33 $10.;
FORMAT BONUS_34 $10.;
FORMAT BONUS_35 $10.;
FORMAT BONUS_36 $10.;
FORMAT BONUS_37 $10.;
FORMAT BONUS_38 $10.;
FORMAT BONUS_39 $10.;
FORMAT BONUS_40 $10.;


INPUT

ROW_ID
X
AGE
Turnover $
type $
BUSINESSTRAVEL $
DAILYRATE
DEPARTMENT $
DISTANCEFROMHOME
EDUCATION
EDUCATIONFIELD $
EMPLOYEECOUNT
EMPLOYEENUMBER
ENVIRONMENTSATISFACTION
GENDER $
HOURLYRATE
JOBINVOLVEMENT
JOBLEVEL
JOBROLE $
JOBSATISFACTION
MARITALSTATUS $
MONTHLYINCOME
MONTHLYRATE
NUMCOMPANIESWORKED
OVER18 $
OVERTIME $
PERCENTSALARYHIKE
PERFORMANCERATING
RELATIONSHIPSATISFACTION
STANDARDHOURS
STOCKOPTIONLEVEL
TOTALWORKINGYEARS
TRAININGTIMESLASTYEAR
WORKLIFEBALANCE
YEARSATCOMPANY
YEARSINCURRENTROLE
YEARSSINCELASTPROMOTION
YEARSWITHCURRMANAGER
BONUS_1 $
BONUS_2 $
BONUS_3 $
BONUS_4 $
BONUS_5 $
BONUS_6 $
BONUS_7 $
BONUS_8 $
BONUS_9 $
BONUS_10 $
BONUS_11 $
BONUS_12 $
BONUS_13 $
BONUS_14 $
BONUS_15 $
BONUS_16 $
BONUS_17 $
BONUS_18 $
BONUS_19 $
BONUS_20 $
BONUS_21 $
BONUS_22 $
BONUS_23 $
BONUS_24 $
BONUS_25 $
BONUS_26 $
BONUS_27 $
BONUS_28 $
BONUS_29 $
BONUS_30 $
BONUS_31 $
BONUS_32 $
BONUS_33 $
BONUS_34 $
BONUS_35 $
BONUS_36 $
BONUS_37 $
BONUS_38 $
BONUS_39 $
BONUS_40 $

;
RUN;
/*NOTE: The data set WORK.EMP_DATA_RAW has 1470 observations and 77 variables.*/


DATA SASDATA.Proj_2;
SET EMP_DATA_RAW;

IF type = "0" THEN CENSORED = 1;
ELSE CENSORED= 0;


TENURE = YEARSATCOMPANY;

RUN;
/* NOTE: The data set SASDATA.PROJ_2 has 1470 observations and 79 variables. */

proc contents data= SASDATA.PROJ_2;
run;

/*Calculation for same hazard for different types of events*/
*Find whether the hazard rates are all same;
data sasdata.proj_2_data;
set SASDATA.PROJ_2;
length event_type $50.;
if type='0' then event_type="No turnover"; else 
if type='1' then event_type="retirement"; else 
if type='2' then event_type="Voluntary Resignation"; else 
if type='3' then event_type="Involuntary Resignation"; else 
event_type="Job Termination";
run; 
PROC FREQ data=SASDATA.PROJ_2_data;
	WHERE type ne '0';
	TABLES event_type /chisq;
RUN;
proc freq data=SASDATA.PROJ_2_data;
tables type;
run;
/*Graphically test for linear relation between type hazards*/
DATA retirement; /*create retirement exit data*/
  SET SASDATA.PROJ_2_data;
  event=(type='1');  /*this is for censoring out other types, another way to write if statement*/
  type='retirement';
DATA vol_resig;  /*create Voluntary Resignation exit data*/
  SET SASDATA.PROJ_2_data;
  event=(type='2');
  type='vol_resig';
DATA invol_resig; /*create Involuntary Resignation exit data*/
  SET SASDATA.PROJ_2_data;
  event=(type='3');
  type='invol_resig';
DATA job_termination; /*create Job Termination exit data*/
  SET SASDATA.PROJ_2_data;
  event=(type='4');
  type='job_termination';
  DATA combine; /*we combined the datasets to use them as strata in the graphical analysis*/
  SET retirement vol_resig invol_resig job_termination;
PROC LIFETEST DATA=COMBINE PLOTS=LLS;  /*LLS plot is requested*/
  TIME tenure*event(0);
  STRATA type /diff=all;
RUN;

/* ######### To convert 'type' from char to num ############# */
data SASDATA.PROJ_2_data;
set SASDATA.PROJ_2_data;
new_type=input(type,5.);
run;
proc contents data=SASDATA.PROJ_2_data;
run;
proc freq data=SASDATA.PROJ_2_data;
tables new_type;
run;
/*test to check whether we can use the same coefficients for Voluntary and 
Involuntary Resignation exits*/
/* ####### both combined #### */
PROC PHREG DATA=SASDATA.PROJ_2_data;
CLASS BUSINESSTRAVEL
EDUCATIONFIELD
GENDER
JOBROLE
MARITALSTATUS
OVERTIME;

   MODEL tenure*new_type(0,1,4)=
AGE
BUSINESSTRAVEL
DAILYRATE
DISTANCEFROMHOME
EDUCATION
EDUCATIONFIELD
ENVIRONMENTSATISFACTION
GENDER
HOURLYRATE
JOBINVOLVEMENT
JOBLEVEL
JOBROLE
JOBSATISFACTION
MARITALSTATUS
MONTHLYINCOME
MONTHLYRATE
NUMCOMPANIESWORKED
OVERTIME
PERCENTSALARYHIKE
PERFORMANCERATING
RELATIONSHIPSATISFACTION
STANDARDHOURS
STOCKOPTIONLEVEL
TOTALWORKINGYEARS
TRAININGTIMESLASTYEAR
WORKLIFEBALANCE
YEARSINCURRENTROLE
YEARSSINCELASTPROMOTION
YEARSWITHCURRMANAGER
;
   STRATA department;
/* ############### involuntary resignation ################## */
PROC PHREG DATA=SASDATA.PROJ_2_data;
CLASS BUSINESSTRAVEL
EDUCATIONFIELD
GENDER
JOBROLE
MARITALSTATUS
OVERTIME;
   MODEL tenure*new_type(0,1,2,4)=
AGE
BUSINESSTRAVEL
DAILYRATE
DISTANCEFROMHOME
EDUCATION
EDUCATIONFIELD
ENVIRONMENTSATISFACTION
GENDER
HOURLYRATE
JOBINVOLVEMENT
JOBLEVEL
JOBROLE
JOBSATISFACTION
MARITALSTATUS
MONTHLYINCOME
MONTHLYRATE
NUMCOMPANIESWORKED
OVERTIME
PERCENTSALARYHIKE
PERFORMANCERATING
RELATIONSHIPSATISFACTION
STANDARDHOURS
STOCKOPTIONLEVEL
TOTALWORKINGYEARS
TRAININGTIMESLASTYEAR
WORKLIFEBALANCE
YEARSINCURRENTROLE
YEARSSINCELASTPROMOTION
YEARSWITHCURRMANAGER
;
   STRATA department;
/* ############ voluntary resignation ############# */
PROC PHREG DATA=SASDATA.PROJ_2_data;
CLASS BUSINESSTRAVEL
EDUCATIONFIELD
GENDER
JOBROLE
MARITALSTATUS
OVERTIME;
   MODEL tenure*new_type(0,1,3,4)=
AGE
BUSINESSTRAVEL
DAILYRATE
DISTANCEFROMHOME
EDUCATION
EDUCATIONFIELD
ENVIRONMENTSATISFACTION
GENDER
HOURLYRATE
JOBINVOLVEMENT
JOBLEVEL
JOBROLE
JOBSATISFACTION
MARITALSTATUS
MONTHLYINCOME
MONTHLYRATE
NUMCOMPANIESWORKED
OVERTIME
PERCENTSALARYHIKE
PERFORMANCERATING
RELATIONSHIPSATISFACTION
STANDARDHOURS
STOCKOPTIONLEVEL
TOTALWORKINGYEARS
TRAININGTIMESLASTYEAR
WORKLIFEBALANCE
YEARSINCURRENTROLE
YEARSSINCELASTPROMOTION
YEARSWITHCURRMANAGER
;
   STRATA department;


DATA LogRatioTest_VolunInVolun;
	Nested = 1296.297;
	Voluntary_Resig = 739.988;
	Involuntary_Resig = 431.756;
	
	Total = Voluntary_Resig + Involuntary_Resig;
	Diff = Nested - Total;

	P_value = 1 - probchi(Diff,29); *58 coef. in 2 models - 29 coef. in nested;
RUN;

PROC PRINT DATA = LogRatioTest_VolunInVolun;
	FORMAT P_Value 5.3;
RUN;
/*test to check whether we can use the same coefficients for Job Termination(4) and 
Involuntary Resignation(3) exits*/

/* ######## both combined ###### */
PROC PHREG DATA=SASDATA.PROJ_2_data;
CLASS BUSINESSTRAVEL
EDUCATIONFIELD
GENDER
JOBROLE
MARITALSTATUS
OVERTIME;

   MODEL tenure*new_type(0,1,2)=
AGE
BUSINESSTRAVEL
DAILYRATE
DISTANCEFROMHOME
EDUCATION
EDUCATIONFIELD
ENVIRONMENTSATISFACTION
GENDER
HOURLYRATE
JOBINVOLVEMENT
JOBLEVEL
JOBROLE
JOBSATISFACTION
MARITALSTATUS
MONTHLYINCOME
MONTHLYRATE
NUMCOMPANIESWORKED
OVERTIME
PERCENTSALARYHIKE
PERFORMANCERATING
RELATIONSHIPSATISFACTION
STANDARDHOURS
STOCKOPTIONLEVEL
TOTALWORKINGYEARS
TRAININGTIMESLASTYEAR
WORKLIFEBALANCE
YEARSINCURRENTROLE
YEARSSINCELASTPROMOTION
YEARSWITHCURRMANAGER
;
   STRATA department;

/* ############ involuntary resignation ################# */
PROC PHREG DATA=SASDATA.PROJ_2_data;
CLASS BUSINESSTRAVEL
EDUCATIONFIELD
GENDER
JOBROLE
MARITALSTATUS
OVERTIME;
   MODEL tenure*new_type(0,1,2,4)=
AGE
BUSINESSTRAVEL
DAILYRATE
DISTANCEFROMHOME
EDUCATION
EDUCATIONFIELD
ENVIRONMENTSATISFACTION
GENDER
HOURLYRATE
JOBINVOLVEMENT
JOBLEVEL
JOBROLE
JOBSATISFACTION
MARITALSTATUS
MONTHLYINCOME
MONTHLYRATE
NUMCOMPANIESWORKED
OVERTIME
PERCENTSALARYHIKE
PERFORMANCERATING
RELATIONSHIPSATISFACTION
STANDARDHOURS
STOCKOPTIONLEVEL
TOTALWORKINGYEARS
TRAININGTIMESLASTYEAR
WORKLIFEBALANCE
YEARSINCURRENTROLE
YEARSSINCELASTPROMOTION
YEARSWITHCURRMANAGER
;
   STRATA department;
   
/* ##### job termination ############### */
PROC PHREG DATA=SASDATA.PROJ_2_data;
CLASS BUSINESSTRAVEL
EDUCATIONFIELD
GENDER
JOBROLE
MARITALSTATUS
OVERTIME;
   MODEL tenure*new_type(0,1,2,3)=
AGE
BUSINESSTRAVEL
DAILYRATE
DISTANCEFROMHOME
EDUCATION
EDUCATIONFIELD
ENVIRONMENTSATISFACTION
GENDER
HOURLYRATE
JOBINVOLVEMENT
JOBLEVEL
JOBROLE
JOBSATISFACTION
MARITALSTATUS
MONTHLYINCOME
MONTHLYRATE
NUMCOMPANIESWORKED
OVERTIME
PERCENTSALARYHIKE
PERFORMANCERATING
RELATIONSHIPSATISFACTION
STANDARDHOURS
STOCKOPTIONLEVEL
TOTALWORKINGYEARS
TRAININGTIMESLASTYEAR
WORKLIFEBALANCE
YEARSINCURRENTROLE
YEARSSINCELASTPROMOTION
YEARSWITHCURRMANAGER
;
   STRATA department;


DATA LogRatioTest_InVolun_JobTerm;
	Nested = 770.863;
        Involuntary_Resig = 431.756;
        Job_Termination = 273.771;
	
	Total = Job_Termination + Involuntary_Resig;
	Diff = Nested - Total;

	P_value = 1 - probchi(Diff,29); *58 coef. in 2 models - 29 coef. in nested;
RUN;

PROC PRINT DATA = LogRatioTest_InVolun_JobTerm;
	FORMAT P_Value 5.3;
RUN;

proc freq data=SASDATA.PROJ_2_data;
tables jobinvolvement;
run;
/*test to check whether retirement is different from other event type exits*/
/* ####### combined #### */
/* ##### 16 model variables ### */
PROC PHREG DATA=SASDATA.PROJ_2_data;
CLASS BUSINESSTRAVEL
EDUCATIONFIELD
GENDER
JOBROLE
MARITALSTATUS
OVERTIME
department
;

   MODEL tenure*new_type(0)=
/* AGE */
BUSINESSTRAVEL
/* DAILYRATE */
DISTANCEFROMHOME
/* EDUCATION */
EDUCATIONFIELD
ENVIRONMENTSATISFACTION
GENDER
/* HOURLYRATE */
JOBINVOLVEMENT
/* JOBLEVEL */
JOBROLE
JOBSATISFACTION
MARITALSTATUS
/* MONTHLYINCOME */
/* MONTHLYRATE */
NUMCOMPANIESWORKED
OVERTIME
/* PERCENTSALARYHIKE */
/* PERFORMANCERATING */
RELATIONSHIPSATISFACTION
/* STANDARDHOURS */
/* STOCKOPTIONLEVEL */
TOTALWORKINGYEARS
TRAININGTIMESLASTYEAR
/* WORKLIFEBALANCE */
YEARSINCURRENTROLE
/* YEARSSINCELASTPROMOTION */
YEARSWITHCURRMANAGER
/* department */
/ties=efron

;

/* ####### ALL EVENT TYPES EXCEPT RETIREMENT ############# */
/* #### 17 model variables #### */
PROC PHREG DATA=SASDATA.PROJ_2_data;
CLASS BUSINESSTRAVEL
EDUCATIONFIELD
GENDER
JOBROLE
MARITALSTATUS
OVERTIME
department
;

   MODEL tenure*new_type(0,1)=
AGE
BUSINESSTRAVEL
/* DAILYRATE */
DISTANCEFROMHOME
/* EDUCATION */
/* EDUCATIONFIELD */
ENVIRONMENTSATISFACTION
GENDER
/* HOURLYRATE */
JOBINVOLVEMENT
/* JOBLEVEL */
JOBROLE
JOBSATISFACTION
MARITALSTATUS
/* MONTHLYINCOME */
/* MONTHLYRATE */
NUMCOMPANIESWORKED
OVERTIME
/* PERCENTSALARYHIKE */
/* PERFORMANCERATING */
RELATIONSHIPSATISFACTION
/* STANDARDHOURS */
STOCKOPTIONLEVEL
TOTALWORKINGYEARS
TRAININGTIMESLASTYEAR
/* WORKLIFEBALANCE */
YEARSINCURRENTROLE
/* YEARSSINCELASTPROMOTION */
YEARSWITHCURRMANAGER
/* department */
/ties=efron

;


/* ####### ONLY RETIREMENT #### */
/* #### 8 model variables ##### */

PROC PHREG DATA=SASDATA.PROJ_2_data;
CLASS BUSINESSTRAVEL
EDUCATIONFIELD
GENDER
JOBROLE
MARITALSTATUS
OVERTIME
department
;

   MODEL tenure*new_type(0,2,3,4)=
AGE
BUSINESSTRAVEL
/* DAILYRATE */
/* DISTANCEFROMHOME */
/* EDUCATION */
/* EDUCATIONFIELD */
/* ENVIRONMENTSATISFACTION */
GENDER
/* HOURLYRATE */
JOBINVOLVEMENT
/* JOBLEVEL */
/* JOBROLE */
/* JOBSATISFACTION */
/* MARITALSTATUS */
/* MONTHLYINCOME */
/* MONTHLYRATE */
/* NUMCOMPANIESWORKED */
OVERTIME
/* PERCENTSALARYHIKE */
/* PERFORMANCERATING */
/* RELATIONSHIPSATISFACTION */
/* STANDARDHOURS */
/* STOCKOPTIONLEVEL */
TOTALWORKINGYEARS
/* TRAININGTIMESLASTYEAR */
/* WORKLIFEBALANCE */
YEARSINCURRENTROLE
/* YEARSSINCELASTPROMOTION */
YEARSWITHCURRMANAGER
/* department */


/rl ties=efron;
   
DATA LogRatioTest_Retirement;
	Nested = 2224.642;
        Retirement = 179.770;
        Except_Retirement=1921.559; 
       
	
	Total = Retirement + Except_Retirement;
	Diff = Nested - Total;

	P_value = 1 - probchi(Diff,9); *8+17=25 coef. in retirement & except_retirement model - 16 coef. in nested;
RUN;

PROC PRINT DATA = LogRatioTest_Retirement;
	FORMAT P_Value 5.3;
RUN;

/*test to check whether we can use the same coefficients for Voluntary and 
Involuntary Resignation exits*/
/* ####### both combined #### */
/* ###### 15 variables ###### */
PROC PHREG DATA=SASDATA.PROJ_2_data;
CLASS BUSINESSTRAVEL
EDUCATIONFIELD
GENDER
JOBROLE
MARITALSTATUS
OVERTIME
department;

   MODEL tenure*new_type(0,1,4)=
AGE
BUSINESSTRAVEL
/* DAILYRATE */
DISTANCEFROMHOME
/* EDUCATION */
/* EDUCATIONFIELD */
ENVIRONMENTSATISFACTION
/* GENDER */
/* HOURLYRATE */
JOBINVOLVEMENT
/* JOBLEVEL */
JOBROLE
JOBSATISFACTION
/* MARITALSTATUS */
/* MONTHLYINCOME */
/* MONTHLYRATE */
NUMCOMPANIESWORKED
OVERTIME
/* PERCENTSALARYHIKE */
/* PERFORMANCERATING */
RELATIONSHIPSATISFACTION
/* STANDARDHOURS */
STOCKOPTIONLEVEL
TOTALWORKINGYEARS
TRAININGTIMESLASTYEAR
/* WORKLIFEBALANCE */
YEARSINCURRENTROLE
/* YEARSSINCELASTPROMOTION */
YEARSWITHCURRMANAGER
/* department */
/ties=efron;
 
/* ############### involuntary resignation ################## */
/* ##### 11 variables #### */
PROC PHREG DATA=SASDATA.PROJ_2_data;
CLASS BUSINESSTRAVEL
EDUCATIONFIELD
GENDER
JOBROLE
MARITALSTATUS
OVERTIME
department;
   MODEL tenure*new_type(0,1,2,4)=
/* AGE */
BUSINESSTRAVEL
/* DAILYRATE */
DISTANCEFROMHOME
/* EDUCATION */
/* EDUCATIONFIELD */
/* ENVIRONMENTSATISFACTION */
/* GENDER */
/* HOURLYRATE */
JOBINVOLVEMENT
/* JOBLEVEL */
JOBROLE
JOBSATISFACTION
/* MARITALSTATUS */
/* MONTHLYINCOME */
/* MONTHLYRATE */
NUMCOMPANIESWORKED
OVERTIME
/* PERCENTSALARYHIKE */
/* PERFORMANCERATING */
/* RELATIONSHIPSATISFACTION */
/* STANDARDHOURS */
/* STOCKOPTIONLEVEL */
TOTALWORKINGYEARS
TRAININGTIMESLASTYEAR
/* WORKLIFEBALANCE */
YEARSINCURRENTROLE
/* YEARSSINCELASTPROMOTION */
YEARSWITHCURRMANAGER
/* department */
/ties=efron;
  
/* ############ voluntary resignation ############# */
/* ##### 15 variables #### */
PROC PHREG DATA=SASDATA.PROJ_2_data;
CLASS BUSINESSTRAVEL
EDUCATIONFIELD
GENDER
JOBROLE
MARITALSTATUS
OVERTIME
department;
   MODEL tenure*new_type(0,1,3,4)=
AGE
BUSINESSTRAVEL
/* DAILYRATE */
DISTANCEFROMHOME
/* EDUCATION */
/* EDUCATIONFIELD */
ENVIRONMENTSATISFACTION
/* GENDER */
/* HOURLYRATE */
/* JOBINVOLVEMENT */
/* JOBLEVEL */
JOBROLE
JOBSATISFACTION
MARITALSTATUS
/* MONTHLYINCOME */
/* MONTHLYRATE */
NUMCOMPANIESWORKED
OVERTIME
/* PERCENTSALARYHIKE */
/* PERFORMANCERATING */
RELATIONSHIPSATISFACTION
/* STANDARDHOURS */
STOCKOPTIONLEVEL
TOTALWORKINGYEARS
TRAININGTIMESLASTYEAR
/* WORKLIFEBALANCE */
YEARSINCURRENTROLE
/* YEARSSINCELASTPROMOTION */
YEARSWITHCURRMANAGER
/* department */
/ties=efron;
  

DATA LogRatioTest_VolunInVolun;
	Nested = 1539.325;
	Voluntary_Resig = 906.679;
	Involuntary_Resig = 543.523;
	
	Total = Voluntary_Resig + Involuntary_Resig;
	Diff = Nested - Total;

	P_value = 1 - probchi(Diff,29); *15+ 11=coef. in voluntary & involuntary models - 29 coef. in nested;
RUN;

PROC PRINT DATA = LogRatioTest_VolunInVolun;
	FORMAT P_Value 5.3;
RUN;



