DM LOG 'CLEAR' LOG;
%LET PATH = P:\SurvivalAnalytics\Project 1;
LIBNAME SASDATA "&PATH.\SASDATA";
OPTIONS COMPRESS=YES;

DATA SASDATA.EMP_DATA_RAW;
	INFILE "&PATH.\RAWDATA\FermaLogis.csv" DELIMITER=',' DSD FIRSTOBS=2 TRUNCOVER;
	INFORMAT ROW_ID BEST32.;
	INFORMAT X BEST32.;
	INFORMAT AGE BEST32.;
	INFORMAT ATTRITION $10.;
	INFORMAT BUSINESSTRAVEL $100.;
	INFORMAT DAILYRATE BEST32.;
	INFORMAT DEPARTMENT $100.;
	INFORMAT DISTANCEFROMHOME BEST32.;
	INFORMAT EDUCATION BEST32.;
	INFORMAT EDUCATIONFIELD $100.;
	INFORMAT EMPLOYEECOUNT BEST32.;
	INFORMAT EMPLOYEENUMBER BEST32.;
	INFORMAT ENVIRONMENTSATISFACTION BEST32.;
	INFORMAT GENDER $10.;
	INFORMAT HOURLYRATE BEST32.;
	INFORMAT JOBINVOLVEMENT BEST32.;
	INFORMAT JOBLEVEL BEST32.;
	INFORMAT JOBROLE $100.;
	INFORMAT JOBSATISFACTION BEST32.;
	INFORMAT MARITALSTATUS $50.;
	INFORMAT MONTHLYINCOME BEST32.;
	INFORMAT MONTHLYRATE BEST32.;
	INFORMAT NUMCOMPANIESWORKED BEST32.;
	INFORMAT OVER18 $10.;
	INFORMAT OVERTIME $10.;
	INFORMAT PERCENTSALARYHIKE BEST32.;
	INFORMAT PERFORMANCERATING BEST32.;
	INFORMAT RELATIONSHIPSATISFACTION BEST32.;
	INFORMAT STANDARDHOURS BEST32.;
	INFORMAT STOCKOPTIONLEVEL BEST32.;
	INFORMAT TOTALWORKINGYEARS BEST32.;
	INFORMAT TRAININGTIMESLASTYEAR BEST32.;
	INFORMAT WORKLIFEBALANCE BEST32.;
	INFORMAT YEARSATCOMPANY BEST32.;
	INFORMAT YEARSINCURRENTROLE BEST32.;
	INFORMAT YEARSSINCELASTPROMOTION BEST32.;
	INFORMAT YEARSWITHCURRMANAGER BEST32.;
	INFORMAT BONUS_1 $10.;
	INFORMAT BONUS_2 $10.;
	INFORMAT BONUS_3 $10.;
	INFORMAT BONUS_4 $10.;
	INFORMAT BONUS_5 $10.;
	INFORMAT BONUS_6 $10.;
	INFORMAT BONUS_7 $10.;
	INFORMAT BONUS_8 $10.;
	INFORMAT BONUS_9 $10.;
	INFORMAT BONUS_10 $10.;
	INFORMAT BONUS_11 $10.;
	INFORMAT BONUS_12 $10.;
	INFORMAT BONUS_13 $10.;
	INFORMAT BONUS_14 $10.;
	INFORMAT BONUS_15 $10.;
	INFORMAT BONUS_16 $10.;
	INFORMAT BONUS_17 $10.;
	INFORMAT BONUS_18 $10.;
	INFORMAT BONUS_19 $10.;
	INFORMAT BONUS_20 $10.;
	INFORMAT BONUS_21 $10.;
	INFORMAT BONUS_22 $10.;
	INFORMAT BONUS_23 $10.;
	INFORMAT BONUS_24 $10.;
	INFORMAT BONUS_25 $10.;
	INFORMAT BONUS_26 $10.;
	INFORMAT BONUS_27 $10.;
	INFORMAT BONUS_28 $10.;
	INFORMAT BONUS_29 $10.;
	INFORMAT BONUS_30 $10.;
	INFORMAT BONUS_31 $10.;
	INFORMAT BONUS_32 $10.;
	INFORMAT BONUS_33 $10.;
	INFORMAT BONUS_34 $10.;
	INFORMAT BONUS_35 $10.;
	INFORMAT BONUS_36 $10.;
	INFORMAT BONUS_37 $10.;
	INFORMAT BONUS_38 $10.;
	INFORMAT BONUS_39 $10.;
	INFORMAT BONUS_40 $10.;
	FORMAT ROW_ID BEST32.;
	FORMAT X BEST32.;
	FORMAT AGE BEST32.;
	FORMAT ATTRITION $10.;
	FORMAT BUSINESSTRAVEL $100.;
	FORMAT DAILYRATE BEST32.;
	FORMAT DEPARTMENT $100.;
	FORMAT DISTANCEFROMHOME BEST32.;
	FORMAT EDUCATION BEST32.;
	FORMAT EDUCATIONFIELD $100.;
	FORMAT EMPLOYEECOUNT BEST32.;
	FORMAT EMPLOYEENUMBER BEST32.;
	FORMAT ENVIRONMENTSATISFACTION BEST32.;
	FORMAT GENDER $10.;
	FORMAT HOURLYRATE BEST32.;
	FORMAT JOBINVOLVEMENT BEST32.;
	FORMAT JOBLEVEL BEST32.;
	FORMAT JOBROLE $100.;
	FORMAT JOBSATISFACTION BEST32.;
	FORMAT MARITALSTATUS $50.;
	FORMAT MONTHLYINCOME BEST32.;
	FORMAT MONTHLYRATE BEST32.;
	FORMAT NUMCOMPANIESWORKED BEST32.;
	FORMAT OVER18 $10.;
	FORMAT OVERTIME $10.;
	FORMAT PERCENTSALARYHIKE BEST32.;
	FORMAT PERFORMANCERATING BEST32.;
	FORMAT RELATIONSHIPSATISFACTION BEST32.;
	FORMAT STANDARDHOURS BEST32.;
	FORMAT STOCKOPTIONLEVEL BEST32.;
	FORMAT TOTALWORKINGYEARS BEST32.;
	FORMAT TRAININGTIMESLASTYEAR BEST32.;
	FORMAT WORKLIFEBALANCE BEST32.;
	FORMAT YEARSATCOMPANY BEST32.;
	FORMAT YEARSINCURRENTROLE BEST32.;
	FORMAT YEARSSINCELASTPROMOTION BEST32.;
	FORMAT YEARSWITHCURRMANAGER BEST32.;
	FORMAT BONUS_1 $10.;
	FORMAT BONUS_2 $10.;
	FORMAT BONUS_3 $10.;
	FORMAT BONUS_4 $10.;
	FORMAT BONUS_5 $10.;
	FORMAT BONUS_6 $10.;
	FORMAT BONUS_7 $10.;
	FORMAT BONUS_8 $10.;
	FORMAT BONUS_9 $10.;
	FORMAT BONUS_10 $10.;
	FORMAT BONUS_11 $10.;
	FORMAT BONUS_12 $10.;
	FORMAT BONUS_13 $10.;
	FORMAT BONUS_14 $10.;
	FORMAT BONUS_15 $10.;
	FORMAT BONUS_16 $10.;
	FORMAT BONUS_17 $10.;
	FORMAT BONUS_18 $10.;
	FORMAT BONUS_19 $10.;
	FORMAT BONUS_20 $10.;
	FORMAT BONUS_21 $10.;
	FORMAT BONUS_22 $10.;
	FORMAT BONUS_23 $10.;
	FORMAT BONUS_24 $10.;
	FORMAT BONUS_25 $10.;
	FORMAT BONUS_26 $10.;
	FORMAT BONUS_27 $10.;
	FORMAT BONUS_28 $10.;
	FORMAT BONUS_29 $10.;
	FORMAT BONUS_30 $10.;
	FORMAT BONUS_31 $10.;
	FORMAT BONUS_32 $10.;
	FORMAT BONUS_33 $10.;
	FORMAT BONUS_34 $10.;
	FORMAT BONUS_35 $10.;
	FORMAT BONUS_36 $10.;
	FORMAT BONUS_37 $10.;
	FORMAT BONUS_38 $10.;
	FORMAT BONUS_39 $10.;
	FORMAT BONUS_40 $10.;
	INPUT ROW_ID X AGE ATTRITION $
BUSINESSTRAVEL $
DAILYRATE DEPARTMENT $
DISTANCEFROMHOME EDUCATION EDUCATIONFIELD $
EMPLOYEECOUNT EMPLOYEENUMBER ENVIRONMENTSATISFACTION GENDER $
HOURLYRATE JOBINVOLVEMENT JOBLEVEL JOBROLE $
JOBSATISFACTION MARITALSTATUS $
MONTHLYINCOME MONTHLYRATE NUMCOMPANIESWORKED OVER18 $
OVERTIME $
PERCENTSALARYHIKE PERFORMANCERATING RELATIONSHIPSATISFACTION STANDARDHOURS 
		STOCKOPTIONLEVEL TOTALWORKINGYEARS TRAININGTIMESLASTYEAR WORKLIFEBALANCE 
		YEARSATCOMPANY YEARSINCURRENTROLE YEARSSINCELASTPROMOTION 
		YEARSWITHCURRMANAGER BONUS_1 $
BONUS_2 $
BONUS_3 $
BONUS_4 $
BONUS_5 $
BONUS_6 $
BONUS_7 $
BONUS_8 $
BONUS_9 $
BONUS_10 $
BONUS_11 $
BONUS_12 $
BONUS_13 $
BONUS_14 $
BONUS_15 $
BONUS_16 $
BONUS_17 $
BONUS_18 $
BONUS_19 $
BONUS_20 $
BONUS_21 $
BONUS_22 $
BONUS_23 $
BONUS_24 $
BONUS_25 $
BONUS_26 $
BONUS_27 $
BONUS_28 $
BONUS_29 $
BONUS_30 $
BONUS_31 $
BONUS_32 $
BONUS_33 $
BONUS_34 $
BONUS_35 $
BONUS_36 $
BONUS_37 $
BONUS_38 $
BONUS_39 $
BONUS_40 $;
RUN;

DATA SASDATA.EMP_PREP;
	SET SASDATA.EMP_DATA_RAW;
	length income $20.;

	IF monthlyincome=. THEN
		income="null";
	ELSE IF monthlyincome <=2911 THEN
		income="low";
	ELSE IF 2911 < monthlyincome <=4919 THEN
		income="medium";
	ELSE IF 4919 < monthlyincome <=8380 THEN
		income="high";
	ELSE
		income="very high";

	IF UPCASE(COMPRESS(ATTRITION))="YES" THEN
		CENSORED=1;
	ELSE
		CENSORED=0;
	TENURE=YEARSATCOMPANY;
RUN;

/* Filter Sales Data */
DATA SASDATA.EMP_PREP_SALES;
	SET SASDATA.EMP_PREP;

	IF DEPARTMENT="Sales";
	WHERE DEPARTMENT eq "Sales";
RUN;

/*################################################################*/
/*################ FINAL MODEL ON Sales DATA #################*/
/*#####################################################################*/
PROC LIFEREG DATA=SASDATA.EMP_PREP_SALES;
	CLASS Gender MaritalStatus OverTime JobInvolvement income;
	MODEL tenure*censored(0)=DISTANCEFROMHOME NUMCOMPANIESWORKED 
		YearsSinceLastPromotion MaritalStatus OverTime JobInvolvement income 
		/Distribution=WEIBULL;
	PROBPLOT;
RUN;

/*##### COMPARE MODELS - R&D ##################*/
DATA CompareModels;
	L_exponential=-212.2867887;
	L_weibull=-199.6381913;
	L_lognormal=-199.9734779;
	L_gamma=-149.9469218;
	LRTEG=-2*(L_exponential - L_gamma);
	LRTEW=-2*(L_exponential - L_weibull);
	LRTWG=-2*(L_weibull - L_gamma);
	LRTLG=-2*(L_lognormal - L_gamma);
	p_valueEG=1 - probchi(LRTEG, 2);
	p_valueEW=1 - probchi(LRTEW, 1);
	p_valueWG=1 - probchi(LRTWG, 1);
	p_valueLG=1 - probchi(LRTLG, 1);
RUN;

PROC PRINT DATA=CompareModels;
RUN;